name = "supaflare-worker"
type = "webpack"
route = ''
account_id = '25c1a646c78aced6918babfd3764a8c2'
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = false
compatibility_date = "2021-10-10"
webpack_config = "webpack.config.js"
kv_namespaces = [ 
  { binding = "SUPAFLARE", id = "a37de0ff79354c91bb42ce0d3d01c9f1" }
]
